### ISSUE TITLE
What is the backward pass in DEQ? Why do we use a fixed-point solver here?

### ISSUE THREAD

**Issue by BraveDrXuTF** [locuslab/torchdeq#5]
In all [parameters](https://github.com/locuslab/torchdeq/blob/main/torchdeq/utils/arg_utils.py) needed by `get_deq` function, I find the backward pass b_solver and b_max_iter, what are they used for? As far as I know, the backward pass refers to backpropagation, and it does not need a fixed-point solver...

**Comment by BurgerAndreas** [comment]
Have a look at the [tutorial colab notebook](https://colab.research.google.com/drive/12HiUnde7qLadeZGGtt7FITnSnbUmJr-I?usp=sharing#scrollTo=056qNdcvDT6q). It explains the different ways to compute gradients quite nicely

**Comment by BraveDrXuTF** [comment]
Thank you, I think I got it.
